replicaCount: 1

php:
  image: "bramalho/fictional-journey-php-api"
  pullPolicy: Always
  tag: latest
  service:
    type: ClusterIP
    port: 9000

nginx:
  image: "bramalho/fictional-journey-nginx-api"
  pullPolicy: Always
  tag: latest
  service:
    type: ClusterIP
    port: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: api.fictional-journey.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
