version: '3'

services:
  admin_php:
    build: ./docker/php-local
    volumes:
      - ./admin/:/var/www/app
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - ~/.composer/docker-cache/:/root/.composer
    depends_on:
      - mysql
      - mongodb

  admin_web:
    image: nginx:1.17.3
    ports:
      - "80:80"
    volumes:
      - ./admin/:/var/www/app
      - ./docker/config/nginx/admin.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - admin_php

  api_php:
    build: ./docker/php-local
    volumes:
      - ./api/:/var/www/app
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - ~/.composer/docker-cache/:/root/.composer
    depends_on:
      - mysql
      - mongodb

  api_web:
    image: nginx:1.17.3
    ports:
      - "88:80"
    volumes:
      - ./api/:/var/www/app
      - ./docker/config/nginx/api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:4.2.10
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null # --quiet
