version: '3'

services:
  admin_php:
    build: ./admin/docker/php
    volumes:
      - ./admin/:/var/www/app:delegated
      - ./admin/docker/php/php.ini:/usr/local/etc/php/php.ini:delegated
      - ~/.composer/docker-cache/:/root/.composer:cached
    depends_on:
      - mysql
      - mongodb

  admin_web:
    image: nginx:1.17.3
    ports:
      - "80:80"
    volumes:
      - ./admin/:/var/www/app:delegated
      - ./admin/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - admin_php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:4.2.10
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null # --quiet
