apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin.fullname" . }}-nginx
  labels:
    {{- include "admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
  selector:
    {{- include "admin.selectorLabels" . | nindent 4 }}
