replicaCount: 1

php:
  image: "bramalho/fictional-journey-php-admin"
  pullPolicy: Always
  tag: latest
  service:
    type: ClusterIP
    port: 9000

nginx:
  image: "bramalho/fictional-journey-nginx-admin"
  pullPolicy: Always
  tag: latest
  service:
    type: ClusterIP
    port: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: admin.fictional-journey.com
      paths: ["/"]
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
