apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admin.fullname" . }}-dotenv
  labels:
    {{- include "admin.labels" . | nindent 4 }}
type: Opaque
data:
  APP_ENV: {{ .Values.php.env.appEnv | b64enc }}
  APP_SECRET: {{ .Values.php.env.appSecret | b64enc }}
  DATABASE_URL: {{ .Values.php.env.databaseURL | b64enc }}
  MONGODB_URL: {{ .Values.php.env.mongoDBURL | b64enc }}
  MONGODB_DB: {{ .Values.php.env.mongoDBDB | b64enc }}
