settings:
  kubeContext: "minikube"
  globalMaxHistory: 5

helmRepos:
  helm-stable: "https://kubernetes-charts.storage.googleapis.com"
  bitnami: "https://charts.bitnami.com/bitnami"

namespaces:
  admin:
    protected: false
  api:
    protected: false

apps:
  mysql:
    namespace: "admin"
    enabled: true
    chart: "helm-stable/mysql"
    version: 1.6.7
    valuesFile: "./mysql/values.yaml"
    priority: -1

  admin:
    namespace: "admin"
    enabled: true
    chart: "./admin"
    version: 0.1.0
    valuesFile: "./admin/values.yaml"

  mongodb:
    namespace: "api"
    enabled: true
    chart: "bitnami/mongodb"
    version: 9.2.4
    valuesFile: "./mongodb/values.yaml"
    priority: -1

  api:
    namespace: "api"
    enabled: true
    chart: "./api"
    version: 0.1.0
    valuesFile: "./api/values.yaml"
